In [1]:
import os
import pandas as pd
import geopandas as gp
import numpy as np
import matplotlib.pyplot as plt

In [2]:
midterm = pd.read_csv('alldata.csv')

In [3]:
midterm

,Unnamed: 0,Unnamed: 0.1,City,Total Days,Poor Days,AQImedian,Zone,City.1,Total_Days,Poor_Days,AQImedian2010,Scale1,scale,Poorday_Rate2020
0,0,0,Seattle,306,14,42,West,Seattle,365,3,41,1.000000,0.838356,16.699346
1,1,1,San Francisco,314,22,45,West,San Francisco,365,14,48,1.000000,0.860274,25.573248
2,2,2,Los Angeles,275,119,81,West,Los Angeles,365,115,77,1.000000,0.753425,157.945455
3,3,3,Denver,366,34,58,Mountain,Denver,365,38,61,1.000000,1.002740,33.907104
4,4,4,Salt Lake City,366,21,50,Mountain,Salt Lake City,365,24,51,1.000000,1.002740,20.942623
5,5,5,Phoenix,366,70,75,Mountain,Phoenix,365,59,74,1.000000,1.002740,69.808743
6,6,6,Chicago,366,28,56,Central,Chicago,365,43,71,1.000000,1.002740,27.923497
7,7,7,St. Louis,366,10,52,Central,St. Louis,365,103,74,1.000000,1.002740,9.972678
8,8,8,Dallas,306,24,49,Central,Dallas,365,28,52,1.000000,0.838356,28.627451
9,9,9,Boston,306,0,42,East,Boston,365,10,47,1.000000,0.838356,0.000000
10,10,10,Washington D.C.,366,3,42,East,Washington D.C.,365,50,55,1.000000,1.002740,2.991803
11,11,11,Miami,275,2,44,East,Miami,365,6,48,1.000000,0.753425,2.654545
12,12,12,Crescent City,264,9,32,West,Cresent City,110,0,12,0.301370,0.723288,12.443182
13,13,13,La Grande,366,9,19,West,La Grande,365,1,25,1.000000,1.002740,8.975410
14,14,14,Idaho Falls,365,5,40,Mountain,Idaho Falls,331,0,43,0.906849,1.000000,5.000000
15,15,15,Yuma,366,3,44,Mountain,Yuma,358,8,40,0.980822,1.002740,2.991803
16,16,16,Topeka,366,4,39,Central,Topeka,365,2,40,1.000000,1.002740,3.989071
17,17,17,St.Cloud,336,0,33,Central,St. Cloud,359,2,36,0.983562,0.920548,0.000000
18,18,18,Barnstable,350,2,35,East,Barnstable,267,7,39,0.731507,0.958904,2.085714
19,19,19,Providence,366,4,42,East,Providence,365,20,44,1.000000,1.002740,3.989071

In [4]:
midterm['lon'] = [-122.33, -122.60, -118.23, 104.99, 118.89, 112.07, 87.62, 90.19, 96.79, 71.05, 77.03, 80.19, 124.20, 118.08, 112.04, 114.62, 95.67, 94.16, 70.30, 71.41]
midterm['lat'] = [47.61, 37.77, 34.05, 39.73, 40.76, 33.44, 41.87, 38.62, 32.77, 42.36, 38.90, 25.76, 41.75, 45.32, 43.49, 32.69, 39.04, 45.55, 41.70, 41.82]

In [5]:
midterm

,Unnamed: 0,Unnamed: 0.1,City,Total Days,Poor Days,AQImedian,Zone,City.1,Total_Days,Poor_Days,AQImedian2010,Scale1,scale,Poorday_Rate2020,lon,lat
0,0,0,Seattle,306,14,42,West,Seattle,365,3,41,1.000000,0.838356,16.699346,-122.33,47.61
1,1,1,San Francisco,314,22,45,West,San Francisco,365,14,48,1.000000,0.860274,25.573248,-122.60,37.77
2,2,2,Los Angeles,275,119,81,West,Los Angeles,365,115,77,1.000000,0.753425,157.945455,-118.23,34.05
3,3,3,Denver,366,34,58,Mountain,Denver,365,38,61,1.000000,1.002740,33.907104,104.99,39.73
4,4,4,Salt Lake City,366,21,50,Mountain,Salt Lake City,365,24,51,1.000000,1.002740,20.942623,118.89,40.76
5,5,5,Phoenix,366,70,75,Mountain,Phoenix,365,59,74,1.000000,1.002740,69.808743,112.07,33.44
6,6,6,Chicago,366,28,56,Central,Chicago,365,43,71,1.000000,1.002740,27.923497,87.62,41.87
7,7,7,St. Louis,366,10,52,Central,St. Louis,365,103,74,1.000000,1.002740,9.972678,90.19,38.62
8,8,8,Dallas,306,24,49,Central,Dallas,365,28,52,1.000000,0.838356,28.627451,96.79,32.77
9,9,9,Boston,306,0,42,East,Boston,365,10,47,1.000000,0.838356,0.000000,71.05,42.36
10,10,10,Washington D.C.,366,3,42,East,Washington D.C.,365,50,55,1.000000,1.002740,2.991803,77.03,38.90
11,11,11,Miami,275,2,44,East,Miami,365,6,48,1.000000,0.753425,2.654545,80.19,25.76
12,12,12,Crescent City,264,9,32,West,Cresent City,110,0,12,0.301370,0.723288,12.443182,124.20,41.75
13,13,13,La Grande,366,9,19,West,La Grande,365,1,25,1.000000,1.002740,8.975410,118.08,45.32
14,14,14,Idaho Falls,365,5,40,Mountain,Idaho Falls,331,0,43,0.906849,1.000000,5.000000,112.04,43.49
15,15,15,Yuma,366,3,44,Mountain,Yuma,358,8,40,0.980822,1.002740,2.991803,114.62,32.69
16,16,16,Topeka,366,4,39,Central,Topeka,365,2,40,1.000000,1.002740,3.989071,95.67,39.04
17,17,17,St.Cloud,336,0,33,Central,St. Cloud,359,2,36,0.983562,0.920548,0.000000,94.16,45.55
18,18,18,Barnstable,350,2,35,East,Barnstable,267,7,39,0.731507,0.958904,2.085714,70.30,41.70
19,19,19,Providence,366,4,42,East,Providence,365,20,44,1.000000,1.002740,3.989071,71.41,41.82

In [6]:
cities = gp.GeoDataFrame(midterm, geometry = gp.points_from_xy(midterm.lon, midterm.lat))
cities

,Unnamed: 0,Unnamed: 0.1,City,Total Days,Poor Days,AQImedian,Zone,City.1,Total_Days,Poor_Days,AQImedian2010,Scale1,scale,Poorday_Rate2020,lon,lat,geometry
0,0,0,Seattle,306,14,42,West,Seattle,365,3,41,1.000000,0.838356,16.699346,-122.33,47.61,POINT (-122.33000 47.61000)
1,1,1,San Francisco,314,22,45,West,San Francisco,365,14,48,1.000000,0.860274,25.573248,-122.60,37.77,POINT (-122.60000 37.77000)
2,2,2,Los Angeles,275,119,81,West,Los Angeles,365,115,77,1.000000,0.753425,157.945455,-118.23,34.05,POINT (-118.23000 34.05000)
3,3,3,Denver,366,34,58,Mountain,Denver,365,38,61,1.000000,1.002740,33.907104,104.99,39.73,POINT (104.99000 39.73000)
4,4,4,Salt Lake City,366,21,50,Mountain,Salt Lake City,365,24,51,1.000000,1.002740,20.942623,118.89,40.76,POINT (118.89000 40.76000)
5,5,5,Phoenix,366,70,75,Mountain,Phoenix,365,59,74,1.000000,1.002740,69.808743,112.07,33.44,POINT (112.07000 33.44000)
6,6,6,Chicago,366,28,56,Central,Chicago,365,43,71,1.000000,1.002740,27.923497,87.62,41.87,POINT (87.62000 41.87000)
7,7,7,St. Louis,366,10,52,Central,St. Louis,365,103,74,1.000000,1.002740,9.972678,90.19,38.62,POINT (90.19000 38.62000)
8,8,8,Dallas,306,24,49,Central,Dallas,365,28,52,1.000000,0.838356,28.627451,96.79,32.77,POINT (96.79000 32.77000)
9,9,9,Boston,306,0,42,East,Boston,365,10,47,1.000000,0.838356,0.000000,71.05,42.36,POINT (71.05000 42.36000)
10,10,10,Washington D.C.,366,3,42,East,Washington D.C.,365,50,55,1.000000,1.002740,2.991803,77.03,38.90,POINT (77.03000 38.90000)
11,11,11,Miami,275,2,44,East,Miami,365,6,48,1.000000,0.753425,2.654545,80.19,25.76,POINT (80.19000 25.76000)
12,12,12,Crescent City,264,9,32,West,Cresent City,110,0,12,0.301370,0.723288,12.443182,124.20,41.75,POINT (124.20000 41.75000)
13,13,13,La Grande,366,9,19,West,La Grande,365,1,25,1.000000,1.002740,8.975410,118.08,45.32,POINT (118.08000 45.32000)
14,14,14,Idaho Falls,365,5,40,Mountain,Idaho Falls,331,0,43,0.906849,1.000000,5.000000,112.04,43.49,POINT (112.04000 43.49000)
15,15,15,Yuma,366,3,44,Mountain,Yuma,358,8,40,0.980822,1.002740,2.991803,114.62,32.69,POINT (114.62000 32.69000)
16,16,16,Topeka,366,4,39,Central,Topeka,365,2,40,1.000000,1.002740,3.989071,95.67,39.04,POINT (95.67000 39.04000)
17,17,17,St.Cloud,336,0,33,Central,St. Cloud,359,2,36,0.983562,0.920548,0.000000,94.16,45.55,POINT (94.16000 45.55000)
18,18,18,Barnstable,350,2,35,East,Barnstable,267,7,39,0.731507,0.958904,2.085714,70.30,41.70,POINT (70.30000 41.70000)
19,19,19,Providence,366,4,42,East,Providence,365,20,44,1.000000,1.002740,3.989071,71.41,41.82,POINT (71.41000 41.82000)

In [ ]:
filepath = 'C:\\Users\\sficc\\gitstuff\\SylvieGITS21\\finalproject\\states.shp'
states = gp.read_file(filepath)

In [ ]:
states.head()

In [ ]:
states = states.to_crs("epsg:4326") #Mercator-projection

In [ ]:
cities

In [ ]:
fig, ax = plt.subplots(figsize=(20,20))
states.plot(ax=ax, color="lightgray", edgecolor="grey", linewidth=0.4, legend = True)
cities.plot(ax=ax,color='red', markersize='Poor_Days', alpha=1.0, categorical=False, legend = True)
ax.axis()
plt.title('Air Quality Index Poor Days: 2020', size=20)
plt.savefig('finalproject/Aqi2020.png')
#plt.axis()
#plt.show()

In [ ]:
fig, ax = plt.subplots(figsize=(20,20))
states.plot(ax=ax, color="lightgray", edgecolor="grey", linewidth=0.4, legend = True)
cities.plot(column = 'Zone', ax=ax, markersize='Poor_Days10', alpha=1.0, categorical=False, legend = True)
ax.axis()
plt.title('Air Quality Index Poor Days: 2010', size=20)
plt.savefig('finalproject/Aqi2010.png')
#plt.axis()
#plt.show()

In [ ]:
import folium

# Make an empty map
m = folium.Map(location=[34,-100], tiles="OpenStreetMap", zoom_start=4)

# Show the map
m

In [ ]:
import folium

for i in range(0,len(cities)):
   folium.Circle(
      location=[cities.iloc[i]['lat'], cities.iloc[i]['lon']],
      popup=cities.iloc[i]['City'],
      radius=float(cities.iloc[i]['Poor_Days'])*2000,
      color='red',
      fill=True,
      fill_color='red'
   ).add_to(m)

# Show the map again
m

In [ ]:
m.save('finalproject/aqidata2020.html')

In [ ]:
import folium

# Make an empty map
m = folium.Map(location=[34,-100], tiles="OpenStreetMap", zoom_start=4)

# Show the map
m

In [ ]:
for i in range(0,len(cities)):
   folium.Circle(
      location=[cities.iloc[i]['lat'], cities.iloc[i]['lon']],
      popup=cities.iloc[i]['City'],
      radius=float(cities.iloc[i]['Poor_Days10'])*2000,
      color='red',
      fill=True,
      fill_color='red'
   ).add_to(m)

# Show the map again
m

In [ ]:
m.save('finalproject/aqidata2010.html')